
tasks:
  - init: npm install
    command: npm run start


vscode:
  extensions:
    - esbenp.prettier-vscode
    - streetsidesoftware.code-spell-checker
    - formulahendry.code-runner
    - rangav.vscode-thunder-client
